name: black
on: [push, workflow_dispatch]
jobs:
  check-black-passes:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $PWD
          pwd
          ls
          pip install black
          black --version
          black -l 120 --check .