name: black
on: [push, workflow_dispatch]
jobs:
  check-black-passes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install black
          black --version
          MAX_LINE_LENGTH=$(grep MAX_LINE_LENGTH= git-hook-pre-commit | cut -f 2 -d '=')
          echo "Using MAX_LINE_LENGTH=$MAX_LINE_LENGTH"
          black -l $MAX_LINE_LENGTH --check .